namespace ShadowViewer.Plugin.Bika.Enums
{
    public enum BikaResourceKey
    {
        Title,
        Tag,
        WebUri,
        About,
        Sponsor,
        BugRequest,
        Dependencies,
        BikaPlugin,
        BikaPluginSettings,
        Shunt,
        ShuntDescription,
        ApiShunt,
        PicShunt,
        ShuntOne,
        ShuntTwo,
        ShuntThree,
        MainSettings,
        Ping,
        Proxy,
        ProxyDescription,
        SystemProxy,
        TimeOut,
        Pinging,
    }
}
