namespace ShadowViewer.Plugin.Bika.Enums
{
    public enum BikaResourceKey
    {
        Title,
        Tag,
        WebUri,
        About,
        Sponsor,
        BugRequest,
        Dependencies,
        BikaPlugin,
        BikaPluginSettings,
        Shunt,
        ShuntDescription,
        ApiShunt,
        PicShunt,
        ShuntOne,
        ShuntTwo,
        ShuntThree,
        MainSettings,
        Ping,
        Proxy,
        ProxyDescription,
        SystemProxy,
        TimeOut,
        Pinging,
        UserName,
        Password,
        Login,
        RememberMe,
        AutoLogin,
        TimeOutMessage1,
        TimeOutMessage2,
        TimeOutMessage3,
        NoAuth,
        NoAuthMessage,
        Unknown,
        BlankLogin,
        LoginTitle,
        Reset,
        Home,
        Classification,
        AutoLoginSuccess,
        LoginSuccess,
        AutoPunchInSuccess,
        BikaKeywords,
        SetError,
        SetSuccess,
        Finished,
        Lock        ,
        Goto        ,
        Refresh     ,
        Page        ,
        Number      ,
        Sort, 
        VD,
        LD,
        DA,
        DD,
        UA,
        ClickGoto,
        ClickSelect,
        IsOpened,
        LockCounts,
    }
}
